### ISSUE TITLE
Logo for "Voltage Pictures"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#102]
Please add the attached logo for the studio "Voltage Pictures" and symlink to "Voltage Films"

thanks!

![voltage-logo2](https://cloud.githubusercontent.com/assets/6506461/10268533/dddfa2e6-6b07-11e5-8772-7f3a44d5ed7d.png)

**Comment by sander1** [comment]
The quality of this image is too low. If you can find a white _or_ black + transparent image or even better, a vector (EPS, SVG) file, please post it here. Thanks!
