### ISSUE TITLE
Logo for "YTV"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#103]
Please add the attached logo for the network "YTV"

thanks!

![ytv_1995_2000_logo_base_by_nicholasjudy456-d854ysd](https://cloud.githubusercontent.com/assets/6506461/10387471/5bebd530-6ead-11e5-87aa-0c03bd2065b4.png)

**Comment by sander1** [comment]
Added in https://github.com/plexinc-plugins/Media-Flags.bundle/commit/430f62e6e0b8a358710e0cafe85474b2139d9713
