### ISSUE TITLE
Logo for "National Geographic (US)"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#109]
Please add the attached logo for the network "National Geographic (US)"

thanks!

![natgeo](https://cloud.githubusercontent.com/assets/6506461/11614254/1f33dca2-9c91-11e5-9514-96c88d90be1c.png)

**Comment by sander1** [comment]
Logo already available, just needed regex update: https://github.com/plexinc-plugins/Media-Flags.bundle/commit/b29e3616f630c3780ab7c32014ad57e1355ccc6d
