### ISSUE TITLE
New/Updated Logos Not Appearing 

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#112]
Not sure what is happening but after 3 or so iterations in updates in Plex ,no new logos or updates are coming through.

**Comment by purevertigo** [comment]
This is still ongoing. Media Flags added in December still don't show up in Plex.

**Comment by purevertigo** [comment]
Plex have said "No set schedule. When needed"

So then who actually is updating these if they haven't been updated since December?

**Comment by purevertigo** [comment]
None of these are being updated by Plex @sander1  Now going on 5 months.

**Comment by sander1** [comment]
Updated with the Plex Media Server 0.9.16.6
