### ISSUE TITLE
Logo for "Scholastic"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#113]
Please add the attached logo for the studio "Scholastic" and add symlink "Scholastic Entertainment".

thanks! 

![scholastic](https://cloud.githubusercontent.com/assets/6506461/13379372/b0462af6-de77-11e5-84ac-98edfbe73975.png)

**Comment by sander1** [comment]
Hi!
Do you have an example of a TV series/movie where this company is listed? I found some series they produced, but the listed networks are always PBS or YTV.
