### ISSUE TITLE
Logo for "Chiller"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#114]
Please add the attached logo for the network "Chiller" AND please update all flags to Plex!

thanks!

![chiller](https://cloud.githubusercontent.com/assets/6506461/13553044/df4d2ce4-e3ce-11e5-8d05-0a546f8c9627.png)

**Comment by sander1** [comment]
The quality of this image is not good enough :( I tried looking up a different image, but I cannot find any on the web...

> AND please update all flags to Plex!

That's out of my hands. I don't know when updated Media Flag bundles are distributed.
