### ISSUE TITLE
Logo for "Chiller"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#115]
Please add the new attached logo for the network "Chiller".

thanks!

![logo](https://cloud.githubusercontent.com/assets/6506461/14465977/55ea5dfc-0118-11e6-9090-b9bc84431c9f.png)

**Comment by sander1** [comment]
Same as before, this image is of too low a quality. Please post vector images, black/transparent or white/transparent images only.
