### ISSUE TITLE
Logo for "trancas international films"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#116]
Please add the attached logo for the studio "trancas international films"

thanks!

![trancas international films](https://cloud.githubusercontent.com/assets/6506461/14737459/7429f71a-08bf-11e6-9ca7-ea11011b91f7.png)

**Comment by sander1** [comment]
This logo is not a vector image or a black/transparent or white/transparent image. I cannot use this to add to the Media Flags bundle...
