### ISSUE TITLE
Logo for "Compass International Pictures"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#117]
Please add the attached logo for the studio "Compass International Pictures"

thanks!

![main](https://cloud.githubusercontent.com/assets/6506461/14737480/934828d8-08bf-11e6-8a35-2e055f76107e.png)

**Comment by sander1** [comment]
This logo is not a vector image or a black/transparent or white/transparent image. I cannot use this to add to the Media Flags bundle...
