### ISSUE TITLE
Try Again Logo for "Chiller"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#118]
What about this one?

logo for the network "Chiller".

thanks!

http://vignette2.wikia.nocookie.net/logopedia/images/f/fa/Chiller_2010.svg/revision/latest?cb=20160415180948

**Comment by sander1** [comment]
Thanks! This is a great source logo! It's been added in https://github.com/plexinc-plugins/Media-Flags.bundle/commit/44e1c9f939f0e6bcaad3385a3a5d868ead71dee8
