### ISSUE TITLE
Updated Logo for "UP TV"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#120]
It seems that the tagline below the logo has been dropped. 
http://uptv.com/

Can it be removed? 
I only have the attached logo for the network "UP TV" though.

thanks!

![561aa0c8-41d5-11e5-883b-b98b8042973d](https://cloud.githubusercontent.com/assets/6506461/14957782/7fa08ca4-10ca-11e6-8264-8fb5a4b09389.png)

**Comment by sander1** [comment]
UPdated: https://github.com/plexinc-plugins/Media-Flags.bundle/commit/cce0971aba9816ef0baf3ee6a0a7663e87db5b10
