### ISSUE TITLE
Logo for "Bleecker Street"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#124]
Please add the attached logo for the studio "Bleecker Street".

thanks!

![full](https://cloud.githubusercontent.com/assets/6506461/15141555/f19a602c-16e3-11e6-902c-21cdcbc7c5dc.png)

**Comment by sander1** [comment]
This is not a vector image, white/transparent or black/transparent image. Can't use this to add to the bundle.

**Comment by sander1** [comment]
Found a usable version of the logo. Added with https://github.com/plexinc-plugins/Media-Flags.bundle/commit/6c53d94a66f56181b9dfd0d9e3cee0cac98b1329

**Comment by purevertigo** [comment]
Thankyou so much!!
