### ISSUE TITLE
Still Issue with logo for "RTÉ One"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#125]
"RTÉ One" not getting scraped properly. I think the accent above the 'e' might have been forgotten to be put in.

thanks

**Comment by sander1** [comment]
This has been updated in https://github.com/plexinc-plugins/Media-Flags.bundle/commit/257b8dfb910556abdd3214161ded98ac1720b84a

**Comment by purevertigo** [comment]
I tested the latest version, its not working for me. I'll wait for your testing. Thanks for the help.

**Comment by sander1** [comment]
[This](https://github.com/plexinc-plugins/Media-Flags.bundle/commit/0daa669f96251b92f75c8d3190f67c41925f0155) makes it work for me.

**Comment by purevertigo** [comment]
Confirmed. Your change makes the logo scrape correctly.

thanks again!
