### ISSUE TITLE
Logo for "Stan"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#126]
Please add the attached logo for the network "Stan"

It's there - just white.

thanks!

![stan](https://cloud.githubusercontent.com/assets/6506461/15287487/83c08a00-1ba6-11e6-8cee-c2e124e5f6e3.png)

**Comment by sander1** [comment]
Added in https://github.com/plexinc-plugins/Media-Flags.bundle/commit/a1d22ecaaee19de023e6cee4cc523efbbf90d19a
