### ISSUE TITLE
Updated Logo for "Starz!"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#128]
The logo for "Starz!" has been updated. New version below and symlink to "Starz"

thanks!

[Starz_2016.zip](https://github.com/plexinc-plugins/Media-Flags.bundle/files/272617/Starz_2016.zip)

**Comment by sander1** [comment]
Thanks for the great source logos! This one has been updated in https://github.com/plexinc-plugins/Media-Flags.bundle/commit/9528354f830bd80626374a978558ed9a3892d663
