### ISSUE TITLE
Logo for "Sony Pictures Animation"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#131]
Please add the attached logo for the studio "Sony Pictures Animation".

thanks!

![sony_pictures_animation_logo](https://cloud.githubusercontent.com/assets/6506461/16478670/7465678c-3ede-11e6-9670-866879b65d9d.png)

**Comment by sander1** [comment]
Added in https://github.com/plexinc-plugins/Media-Flags.bundle/commit/9cf8e28ac2b85c75e5c32293c4bf5d8db5fcb6d2
