### ISSUE TITLE
Logo for "EMI Films"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#132]
Please add the attached logo for the studio "EMI Films" and add symlink to "EMI Film Distributors"

thanks!

http://vignette4.wikia.nocookie.net/logopedia/images/f/ff/EMI_logo.svg/revision/latest?cb=20130327090111

**Comment by sander1** [comment]
Added in 5c2b8b076f7f50884a64390ebb53b994a3b95942
