### ISSUE TITLE
Updated Logo for "DreamWorks"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#136]
Please add the attached updated logo (widely used) for the studio "DreamWorks"

thanks!

http://vignette1.wikia.nocookie.net/logopedia/images/1/11/DreamWorks-SKG-logo.svg/revision/latest?cb=20141124120157

**Comment by sander1** [comment]
According to https://en.wikipedia.org/wiki/DreamWorks and http://logos.wikia.com/wiki/DreamWorks_Pictures the current logo is stil... current.

**Comment by purevertigo** [comment]
Hey Sander1! I noticed that was the case too but I can't find it being used anywhere. I looked on trailers on the web, and movies that I own and they all use the 'SKG' variant.
