### ISSUE TITLE
Logo for "Topps"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#141]
Please add the linked logo for the studio "Topps".

thanks!

http://vignette4.wikia.nocookie.net/logopedia/images/c/ca/Topps.svg/revision/latest?cb=20140619202346

**Comment by sander1** [comment]
For what TV show(s) or movie(s) is Topps the producer or studio? I can't find anything, andlooking at https://en.wikipedia.org/wiki/Topps this isn't a TV/Movie production company. Do you have a link to TVDB, MovieDB or IMDb with a list of their productions?

**Comment by purevertigo** [comment]
An old 80s movie so far..

https://www.themoviedb.org/movie/14443-the-garbage-pail-kids-movie

They are same as Hasbro, created/funded.

**Comment by purevertigo** [comment]
What happened here?
