### ISSUE TITLE
add logo for the former east german film studio DEFA

### ISSUE THREAD

**Issue by OttoKerner** [plexinc-plugins/Media-Flags.bundle#146]
SVG logo https://upload.wikimedia.org/wikipedia/commons/6/6d/DEFA_Logo.svg

above Logo is applicable for the following studio names:
``` 
Deutsche Film AG
DEFA–Filmverleih
DEFA-Studio für Spielfilme
DEFA-Studio für Trickfilme
DEFA-Studio für populärwissenschaftliche Filme
DEFA-Studio für Wochenschau und Dokumentarfilme
```
in short `DEFA-Studio` should cover the latter 4 of these.
there are also variants with spaces before and after the hyphen, like
`DEFA - Studio ...`

sometimes there is also the abbreviation `VEB` in front of the name, so an additional match for
`VEB DEFA` is desirable.

(unfortunately I am totally clueless when it comes to regular expressions)

**Comment by OttoKerner** [comment]
Here is a png version I made earlier after the model of the other logos in the bundle:
![defa](https://cloud.githubusercontent.com/assets/10280992/18137525/e9b9578c-6fa8-11e6-8a43-0585c75ae1b8.png)

**Comment by sander1** [comment]
Hi! Thanks for the logo! This has been added in https://github.com/plexinc-plugins/Media-Flags.bundle/commit/72c31721aacb7bd9ea14289e96fe4d4b952e8b6b
