### ISSUE TITLE
Logo for "Eleven"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#152]
Please update the linked logo for the network "Eleven".

thanks!

http://vignette2.wikia.nocookie.net/logopedia/images/c/c2/Eleven_logo.svg/revision/latest?cb=20111111145003

**Comment by sander1** [comment]
For what show(s) is Eleven the original studio? As far as I can find out, the channel just reruns programmes from "Ten".

**Comment by purevertigo** [comment]
There are quite a few shows the are 'Eleven' originals. 

two off hand are http://thetvdb.com/?tab=series&id=318029&lid=7

and http://thetvdb.com/index.php?id=76719

**Comment by sander1** [comment]
Thanks for the extra info! The logo has been added!
