### ISSUE TITLE
Logo for "RTL 4"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#156]
Please create the linked logo for the network "RTL 4" and symlink to avoid mix-up with other "RTL".

thanks!

http://vignette2.wikia.nocookie.net/logopedia/images/a/af/RTL4.svg/revision/latest?cb=20130914181941

**Comment by sander1** [comment]
This one is already in here. Maybe there's a difference in spelling somewhere, "rtl4" vs "rtl 4" (with a space)?

https://github.com/plexinc-plugins/Media-Flags.bundle/blob/master/Contents/Resources/Studio/rtl4.png

**Comment by purevertigo** [comment]
Yes @sander1 thanks for picking that up.  I see it now. 

Can you please symlink both variations of spelling? 

thanks
