### ISSUE TITLE
Logo for "Sky Atlantic"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#157]
Please create the linked logo for the network "Sky Atlantic" and please symlink so it doesn't get mixed up with the regular Sky channel.

thanks!

http://vignette4.wikia.nocookie.net/logopedia/images/d/d3/Sky_Atlantic.svg/revision/latest?cb=20111101112901

**Comment by purevertigo** [comment]
Can this be added please?

**Comment by sander1** [comment]
I need a "flat" version of the logo so I can convert it to white/transparent. I've been looking, but haven't found one yet.

**Comment by purevertigo** [comment]
OK Cheers @sander1

**Comment by sander1** [comment]
I finally found a version I could work with :) https://github.com/plexinc-plugins/Media-Flags.bundle/commit/3a5ddd722c8fca0f8db99dbc765a01237739ff04

**Comment by purevertigo** [comment]
Legend. Good work. Thanks @sander1
