### ISSUE TITLE
Logo required

### ISSUE THREAD

**Issue by BrendenCA** [plexinc-plugins/Media-Flags.bundle#159]
A logo for brazzers.com,

There are already other such sites logo's uploaded, so I assume this wont be a issue

http://brand.brazzers.com/resources/brazzers/mainlogos/brazzers_logo-primary_color.jpg

http://static.brazzers.com/bzv2/brazzerscom/tour/assets/common/img/logo/brazzers_logo.png

**Comment by dulnefni** [comment]
![stod2](https://cloud.githubusercontent.com/assets/24237842/20693308/60880454-b5d5-11e6-9db7-f75458ca0b04.png)
![ruv](https://cloud.githubusercontent.com/assets/24237842/20693312/69081dd0-b5d5-11e6-88df-b9ec25f48a48.png)

Can you also add "Stöð 2" and "RÚV"

**Comment by sander1** [comment]
Please provide vector images (svg, eps, pdf) or clean black/transparent or white transparent PNG files only.
