### ISSUE TITLE
Logo for "Head Gear Films"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#161]
Please add attached logo for the studio "Head Gear Films".

thanks!

![head-gear](https://cloud.githubusercontent.com/assets/6506461/22403237/522eb270-e665-11e6-835a-81dffea3f49b.png)

**Comment by sander1** [comment]
Logo has been added! Please provide vector images (svg, eps, pdf) or clean black/transparent or white transparent PNG files only next time.

**Comment by purevertigo** [comment]
thanks @sander1 will do.
