### ISSUE TITLE
Logo for "FilmNation Entertainment"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#168]
Please add linked logo for the studio "FilmNation Entertainment".

thanks!

http://vignette2.wikia.nocookie.net/logopedia/images/5/52/FilmNation_Entertainment.svg/revision/latest?cb=20161012171221

**Comment by sander1** [comment]
Added with 331f68add231c81141e00fb4842899ccc1ab72a5
