### ISSUE TITLE
USA Network Logo not showing correctly.

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#17]
For some reason the USA Network logo does not show up in Plex. I think the symlink might be broken. Not sure what is going on. Can you please check this? thankyou.

**Comment by sander1** [comment]
Thanks for the report! This has been fixed in 872480fddf0ab2ca7ddd4e716fb8e1aeb1019242, the updated Media Flags bundle will be released soon!
