### ISSUE TITLE
New updated "Audience Network" Logo

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#18]
Sorry, logo I posted a few days ago is the older one. I have attached the new one. Could you please change flags bundle to reflect this?

cheers

![logo_lg__audience](https://cloud.githubusercontent.com/assets/6506461/6554955/2450682a-c6b5-11e4-8244-cb96a33fcce5.png)

**Comment by sander1** [comment]
I don't see any difference, except for the word "network" not in this one. Wikipedia and Logopedia list the one with "network" as the current one.

**Comment by sander1** [comment]
We can't use the image attached, because it is not black&white and has a shadow.

**Comment by purevertigo** [comment]
OK. If you go to the audience network website then the correct one (sans network) is there. What about dropping the network name from the original I posted? :-)
