### ISSUE TITLE
Logo for "M6"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#23]
Please add the attached logo for the network "M6"

thanks!

![m6_logo_new-1-](https://cloud.githubusercontent.com/assets/6506461/6580215/0b647290-c7a3-11e4-89c8-c5a700f128f3.png)

**Comment by purevertigo** [comment]
alternate png version



![logo m6](https://cloud.githubusercontent.com/assets/6506461/8001970/57c33cd0-0bae-11e5-930a-458cb661a209.png)

**Comment by sander1** [comment]
Please find me a black/white (no grey) PNG (with a transparent background) or a vector version of this logo (.svg, .eps). I can't add this image :(
