### ISSUE TITLE
Logo for "PlayStation Network"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#25]
Please add the attached logo for the network "PlayStation Network"

thanks!

![asd](https://cloud.githubusercontent.com/assets/6506461/6591207/2ffc1348-c810-11e4-89a2-b405c334cfb3.jpg)

**Comment by sander1** [comment]
Which TV series of movie(s) have Playstation Network as their Studio?

**Comment by purevertigo** [comment]
It is a new series just started today. Check it out! 

http://thetvdb.com/?tab=series&id=286943&lid=7

**Comment by sander1** [comment]
Please find me a black/white (no grey) PNG (with a transparent background) or a vector version of this logo (.svg, .eps). I can't add this image :(
