### ISSUE TITLE
FOX studio name not linked to logo properly

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#26]
The Studio name "FOX (US)" does not scrape the "FOX" logo when adding to library.

**Comment by sander1** [comment]
Where is the string "FOX (US)" used (which show(s)) for example?
"fox network" is currently the known value for this studio.

**Comment by purevertigo** [comment]
Sure, 

tvdb has started using it for new shows to distinguish.

example is Gotham  http://thetvdb.com/?tab=series&id=274431&lid=7

thanks

**Comment by sander1** [comment]
Thank you for the info! I've included the new studio names to match the correct icon! I'll release an update for this bundle in a couple of hours.

**Comment by purevertigo** [comment]
thankyou!
