### ISSUE TITLE
ABC studio name not linked to logo properly

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#27]
The Studio name "ABC (AU)" does not scrape the "ABC1" logo when adding to library and should.

**Comment by sander1** [comment]
Where is the string "ABC (AU)" used (which show(s)) for example?
"abc1" and "australian broadcasting" are currently the known values for this studio.

**Comment by purevertigo** [comment]
Sure, 

tvdb has started using it for new shows to distinguish.

example is The Slap   http://thetvdb.com/index.php?id=252325

thanks

**Comment by sander1** [comment]
Thank you for the info! I've included the new studio names to match the correct icon! I'll release an update for this bundle in a couple of hours.

**Comment by purevertigo** [comment]
thankyou!
