### ISSUE TITLE
Logo for "Insurge Pictures"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#29]
Please add the attached logo for the network "Insurge Pictures"

thanks!

![insurge pictures](https://cloud.githubusercontent.com/assets/6506461/7684146/393ad72c-fdc7-11e4-9b98-125b4a1d6025.jpg)

**Comment by purevertigo** [comment]
Alternate Version


![insurge](https://cloud.githubusercontent.com/assets/6506461/8002069/01f10156-0baf-11e5-8e07-67c007fda414.png)

**Comment by sander1** [comment]
Please find me a black/white (no grey) PNG (with a transparent background) or a vector version of this logo (.svg, .eps). I can't add this image :(
