### ISSUE TITLE
Logo for "Australian Children's Television Foundation"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#35]
Please add the attached logo for the network "Australian Children's Television Foundation"

thanks!

![logo_homepage](https://cloud.githubusercontent.com/assets/6506461/8023560/05eba3f0-0d54-11e5-85b1-8b26044443b5.png)

**Comment by sander1** [comment]
Please find me a black/white (no grey) PNG (with a transparent background) or a vector version of this logo (.svg, .eps). I can't add this image :(
