### ISSUE TITLE
"ABC Family" studio name not linked to logo properly and logo needs updating.

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#36]
The Studio name "ABC Family" does not scrape the "ABC Family" logo when adding to library AND also the old logo needs to be updated to the current one attached.

thanks!

![178px-abc_family_logo svg](https://cloud.githubusercontent.com/assets/6506461/8025845/53d4b892-0da7-11e5-8f02-5070e2a8e081.png)

**Comment by sander1** [comment]
Logo updated. Naming and regex look correct and _should_ work. I'll have to setup a test library to check, will do that later on.

**Comment by purevertigo** [comment]
Thanks for updating the logo. 

As of yesterday, the logo does not scrape correctly to ABC family.

thanks!

**Comment by sander1** [comment]
Is this still not working? I just checked and when the studio name is set correctly, the logo shows up as expected.

![screen shot 2015-06-13 at 16 19 26](https://cloud.githubusercontent.com/assets/104684/8144645/4b0afaf6-11e8-11e5-87a4-fa68f20afcc2.jpg)

**Comment by purevertigo** [comment]
Just checked again by manually changing and same thing, not working only displays ABC.

Have the changes been integrated into plex server? (I'm running plex pass version)

**Comment by sander1** [comment]
I just pushed out an updated Media Flags bundle. This update should fix the ABC / ABC Family issue.

**Comment by purevertigo** [comment]
OK. thanks. I will test it and if any problems let you know. Now just for the other new logo requests and all finished!

**Comment by purevertigo** [comment]
Confirmed Working! This can now be closed.
