### ISSUE TITLE
Logo for "YouTube"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#52]
Please add the attached logo for the network "YouTube"

thanks!

![youtube_logo](https://cloud.githubusercontent.com/assets/6506461/8267268/be3ebca6-179c-11e5-9050-b62fed0ed53f.png)

**Comment by sander1** [comment]
Where/with what series or movies is YouTube the studio?

**Comment by purevertigo** [comment]
Alot of independent parties as well as YouTube announcing the funding of new original shows too and shows such as http://thetvdb.com/index.php?tab=series&id=284768&lid=7

thanks!
