### ISSUE TITLE
Existing hasbro.png malformed.

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#68]
The existing 'hasbro.png' has an invisible white box around the logo which should not be part of the logo. Needs to be taken out. Attached.

![hasbro](https://cloud.githubusercontent.com/assets/6506461/8498556/99149962-21cb-11e5-86f0-8d0c733bd1bd.png)

**Comment by sander1** [comment]
Fixed!
