### ISSUE TITLE
Logo for "Marvel" wrong version. Needs to be updated. 

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#72]
Current Marvel logo png is from pre-2013 Logo and should be updated to the same as attached logo as also indicated here http://logos.wikia.com/wiki/Marvel_Comics

thanks!

![8b5c116c-1940-11e5-9326-9567716aa668](https://cloud.githubusercontent.com/assets/6506461/8555586/5d97589a-2534-11e5-96a4-0f51df564836.png)

**Comment by sander1** [comment]
Thanks for noticing! The differences are so small between the pre-2013 en current version! New version has been added!

**Comment by purevertigo** [comment]
thanks! keep up the excellent work mate.
