### ISSUE TITLE
Add symlink for "Entertainment One"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#75]
Add symlinks of
"eOne" and "eOne Entertainment" and "Entertainment One Films" to link to "Entertainment One" logo.

thanks

**Comment by sander1** [comment]
Entertainment One Films: this one already matches the "Entertainment One" regex
eOne Entertainment: added
Also added: E1 Entertainment

I can't find any place where only "eOne" is being used.

**Comment by purevertigo** [comment]
No problem. There you go. Wikipedia has it as an AKA https://en.wikipedia.org/wiki/Entertainment_One

**Comment by sander1** [comment]
Regex updated in d7e3d5efe85cc47b72e4d9c78abe41d702ef7604
