### ISSUE TITLE
Logo for "The Halcyon Company"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#77]
Please add the attached logo for the studio "The Halcyon Company".

thanks!

![the_halcyon_co](https://cloud.githubusercontent.com/assets/6506461/8773666/48fe318a-2f19-11e5-9cee-80c808c57951.png)

**Comment by sander1** [comment]
Unusable logo :( I can't find any usable ones on the net...

**Comment by purevertigo** [comment]
trying again...
