### ISSUE TITLE
Attempt #2 Logo for "The Halcyon Company"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#78]
Please try this. Add the attached logo for the studio "The Halcyon Company".

thanks!

![terminator_salvation_the_future_begins_halcyon_company_0](https://cloud.githubusercontent.com/assets/6506461/8775685/e85fd58a-2f2d-11e5-9ec5-f4aea58e9681.png)

**Comment by sander1** [comment]
That's the best one I could find as well, but it's unusable

**Comment by purevertigo** [comment]
That's OK. Thanks for trying anyway.
