### ISSUE TITLE
Logo for "The Asylum"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#87]
Please add the attached logo for the studio "The Asylum"

thanks!

![the_asylum_logo](https://cloud.githubusercontent.com/assets/6506461/8895330/9b4eddfe-3419-11e5-8035-20058f7b7a0e.png)

**Comment by sander1** [comment]
Can't find a usable logo for this :(

**Comment by purevertigo** [comment]
OK. thanks anyways.
