### ISSUE TITLE
Logo for "Blumhouse Productions"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#88]
Please add the attached logo for the studio "Blumhouse Productions"

thanks!

![blumhouse-productions](https://cloud.githubusercontent.com/assets/6506461/8937677/5cb17784-359d-11e5-8509-ab266bb30ab1.png)

**Comment by sander1** [comment]
No idea what happened, but this is not a clean PNG file...

![screen shot 2015-07-29 at 14 28 18](https://cloud.githubusercontent.com/assets/104684/8957398/87d87e74-35fe-11e5-9792-7963e016e98e.png)

**Comment by purevertigo** [comment]
OK. I'll try again. thanks.
