### ISSUE TITLE
Logo for "CW Seed"

### ISSUE THREAD

**Issue by purevertigo** [plexinc-plugins/Media-Flags.bundle#96]
Please add the attached logo for the network "CW Seed"

thanks!

![hhhhhh](https://cloud.githubusercontent.com/assets/6506461/9568715/e32fbe04-4f94-11e5-9d13-579d4b9ff8be.png)

**Comment by sander1** [comment]
Thanks! It's been added!

**Comment by purevertigo** [comment]
no problem. thanks for the great work!
